#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil author:nil num:1 creator:nil timestamp:nil toc:nil

#+TITLE: The Drawer Alarm
#+AUTHOR: Stephen

#+BEGIN_HTML
  <div class="github-fork-ribbon-wrapper left">
    <div class="github-fork-ribbon">
      <a href="https://github.com/stcd11/9-SC-Alarm">Fork me on GitHub</a>
    </div>
  </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week1</a></li>
      <li><a href="2_Lesson.html">Week2</a></li>
      <li><a href="3_Lesson.html">Week3</a></li>
      <li><a href="4_Lesson.html">Week4</a></li>
      <li><a href="5_Lesson.html">Week5</a></li>
      <li><a href="6_Lesson.html">Week6</a></li>
      <li><a href="assessment.html">Assessment</a></li>
    </ul>
  </div>
#+END_HTML

* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Homework Tasks
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** 1. Sense It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:
- The drawer alarm uses a LDR as a sensor to detect when the drawer is open. 
- Research *three* other types of sensor that could be added to a circuit, and suggest a project they could be used for. 
- For each, find a picture from the web of the sensor.
- E.g. An ultrasonic distance sensor uses ultrasound to detect how far away objects are from it. 
- This could be used to make a reversing sensor for a car.
- Upload your work to the first badge in the homework section.

** 2. Sound It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:
- The drawer alarm uses a small loudspeaker to alert the owner when it is triggered. 
- Read this page: https://www.bournetoinvent.com/projects/mp3/step_4.html and complete the task described at the bottom.

** 3. House It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:
- The housing for the drawer alarm is made from laser-cut 3mm acrylic sheet, separated by some nuts and bolts. 
- Sketch designs for two different housings and label them. 
- They’ll still need to have the switch on the front, somewhere for the LDR and two LEDs, but how you design it is up to you. Indicate approximate dimensions. 
- Where will the PCB go? What holds it together? What’s it made from? Where do the batteries go?
** 4. Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:
- When products are designed for commercial release, it is essential they are tested.
- There are different types of test:
  - Functional testing ensure that the product does what it should. E.g. A microwave oven should stop emitting microwaves when the time set has run out.
  - Performance testing checks that a product performs to a particular standard. E.g. A burlar alarm sensor should be able to detect an intruder from at least 5m away.
  - Safety testing ensures that the product is safe to use. E.g. A glass should be inspected to ensure there are no jagged edges.
  - Visual inspection will ensure that the product looks correct. E.g. In a box of eggs, none should be broken.
  - Durability testing will see if a product will break easily. E.g. A vacuum cleaner should be able to be dropped onto a hard floor from 10cm and still work properly. 
- Answer these questions:
  - Provide at least two reasons why it is important to test an electronic product before mass-producing and selling it.
  - Imagine you were a product test engineer for the drawer alarm. Describe four different tests you could conduct to make sure its suitable to be sold. 
  - For each test, state the type of test (see above) that you are describing.
** 5. Material world
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:
- We tend to use MDF and acrylic in School for much of our making
- We could use lots of other things too, like steel. 
- Materials can be grouped into different types, such as:
  1. [[https://en.wikipedia.org/wiki/Engineered_wood][Man-made boards]]
  2. [[https://en.wikipedia.org/wiki/Hardwood][Hardwoods]]
  3. [[https://en.wikipedia.org/wiki/Softwood][Softwoods]]
  4. [[https://simple.wikipedia.org/wiki/Thermoplastic][Thermoplastics]]
  5. [[https://simple.wikipedia.org/wiki/Thermosetting_polymer][Thermosetting polymers]]
  6. [[http://www.bbc.co.uk/schools/gcsebitesize/design/electronics/materialsrev3.shtml][Ferrous]] metals
  7. [[http://www.bbc.co.uk/schools/gcsebitesize/design/electronics/materialsrev3.shtml][Non-ferrous]] metals
- Write a brief definition of each of the above.
- Provide an example for each. The first one is done for you. E.g.
#+BEGIN_QUOTE
A man-made board is a material made by combining wood with something else (e.g. glue). An example of this is MDF which is made by mixing sawdust and glue together, then pressing it into flat sheets.
#+END_QUOTE
** 6. Evaluate it
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:
- You should now be at the end of this project. 
- To finish up, you will write a short evaluation of your work during this project.
- Write a short evaluation of your performance, considering each of the following:
  - What went well? E.g. Your soldering, your programming work, PCB design?
  - What didn't do so well? E.g. Struggled with coding, didn't get the product finished.
  - What will you do differently in future projects to improve your performance? E.g. Time management, practice soldering, avoid distraction, etc.
